### ISSUE TITLE
ERR_MODULE_NOT_FOUND after updating to 8.2.1

### ISSUE THREAD

**Issue by marcinincreo** [sanity-io/next-sanity#1111]
```js
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/node_modules/.pnpm/@sanity+preview-kit@5.0.31_@sanity+client@6.15.3_react@18.2.0/node_modules/use-sync-external-store/with-selector' imported from /node_modules/.pnpm/@sanity+preview-kit@5.0.31_@sanity+client@6.15.3_react@18.2.0/node_modules/@sanity/preview-kit/dist/hooks.js
Did you mean to import use-sync-external-store@1.2.0_react@18.2.0/node_modules/use-sync-external-store/with-selector.js?
    at new NodeError (node:internal/errors:405:5)
    at finalizeResolution (node:internal/modules/esm/resolve:324:11)
    at moduleResolve (node:internal/modules/esm/resolve:943:10)
    at defaultResolve (node:internal/modules/esm/resolve:1129:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36) {
```

Node - v18.17.0
Next.js - 14.1.3
Sanity - 3.32.0

**Comment by stipsan** [comment]
Could you give [v8.3.1](https://github.com/sanity-io/next-sanity/releases/tag/v8.3.1) a try?

**Comment by marcinincreo** [comment]
@stipsan working correctly now 👍
